call make.bat ABORT 
call make.bat ABS 
call make.bat ACCESS 
call make.bat ALARM 
call make.bat ATOI 
call make.bat ATOL 
call make.bat BCOPY 
call make.bat BRK 
call make.bat BRK2 
call make.bat CALL 
call make.bat CHDIR 
call make.bat CHMOD 
call make.bat CHOWN 
call make.bat CHROOT 
call make.bat CLEANUP 
call make.bat CLOSE 
call make.bat CREAT 
call make.bat CRYPT 
call make.bat CTYPE 
call make.bat DOPRINTF 
call make.bat DUP 
call make.bat DUP2 
call make.bat EXEC 
call make.bat EXIT 
call make.bat FCLOSE 
call make.bat FFLUSH 
call make.bat FGETS 
call make.bat FOPEN 
call make.bat FORK 
call make.bat FPRINTF 
call make.bat FPUTS 
call make.bat FREAD 
call make.bat FREOPEN 
call make.bat FSEEK 
call make.bat FSTAT 
call make.bat FTELL 
call make.bat FWRITE 
call make.bat GETC 
call make.bat GETEGID 
call make.bat GETENV 
call make.bat GETEUID 
call make.bat GETGID 
call make.bat GETGRENT 
call make.bat GETPASS 
call make.bat GETPID 
call make.bat GETPWENT 
call make.bat GETS 
call make.bat GETUID 
call make.bat INDEX 
call make.bat IOCTL 
call make.bat ISATTY 
call make.bat ITOA 
call make.bat KILL 
call make.bat LINK 
call make.bat LSEEK 
call make.bat MALLOC 
call make.bat MESSAGE 
call make.bat MKNOD 
call make.bat MKTEMP 
call make.bat MOUNT 
call make.bat OPEN 
call make.bat PAUSE 
call make.bat PERROR 
call make.bat PIPE 
call make.bat PRINTDAT 
call make.bat PRINTK 
call make.bat PRINTS 
call make.bat PUTC 
call make.bat RAND 
call make.bat READ 
call make.bat REGEXP 
call make.bat REGSUB 
call make.bat RINDEX 
call make.bat SCANF 
call make.bat SETBUF 
call make.bat SETGID 
call make.bat SETUID 
call make.bat SIGNAL 
call make.bat SLEEP 
call make.bat SPRINTF 
call make.bat STAT 
call make.bat STB 
call make.bat STDERR 
call make.bat STIME 
call make.bat STRCAT 
call make.bat STRCMP 
call make.bat STRCPY 
call make.bat STRLEN 
call make.bat STRNCAT 
call make.bat STRNCMP 
call make.bat STRNCPY 
call make.bat SYNC 
call make.bat SYSLIB 
call make.bat TIME 
call make.bat TIMES 
call make.bat UMASK 
call make.bat UMOUNT 
call make.bat UNGETC 
call make.bat UNLINK 
call make.bat UTIME 
call make.bat WAIT 
call make.bat WRITE
masm brksize,,nul,nul >brksize.lst
masm catchsig,,nul,nul >catchsig.lst
masm crtso,,nul,nul >crtso.lst
masm csv,,nul,nul >csv.lst
masm end,,nul,nul >end.lst
masm getutil,,nul,nul >getutil.lst
masm head,,nul,nul >head.lst
masm sendrec,,nul,nul >sendrec.lst
masm setjmp,,nul,nul >setjmp.lst
del mxc86.lib
lib @.\libfiles
